version: "3.1"
services:
  api:
    build: .
    ports:
      - 8000:8000
##### Uncomment this if you want to save updated data between deployments
#    volumes:
#      - ./sql_app.db:/app/sql_app.db



